name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
          ruby-version: 2.6.x
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
          node-version: 10.13.0
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Login to Docker Registry
      uses: azure/docker-login@v1
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Run a multi-line script
      run: |
        echo test project,
        make base_images
    - name: Scan image
      uses: anchore/scan-action@master
      with:
          image-reference: "wshihadeh/rails-base-image-ruby:2.6.4"
    
