name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
          ruby-version: 2.6.x
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
          node-version: 10.13.0
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: wshihadeh/rails-base-image-ruby
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Run a multi-line script
      run: |
        echo test project,
        make base_images
    
