name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby
    - uses: actions/setup-ruby@v1
      with:
          ruby-version: 2.6.3
    - name: Set up Node
      uses: actions/setup-node@v1
      with:
          node-version: 10.13.0
    - name: Install dependencies
      run: |
          sudo apt-get -yqq install libpq-dev chromium-chromedriver
          gem install bundler
          bundle install
          yarn install
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo test project,
        make base_images
